// AID-GENERATED
// =========================================================================
// This class was generated by AID - Abstract Interface Definition          
// DO NOT MODIFY, but use the org.freehep.aid.Aid utility to regenerate it. 
// =========================================================================

//  This file is part of the AIDA library
//  Copyright (C) 2002 by the AIDA team.  All rights reserved.
//  This library is free software and under the terms of the
//  GNU Library General Public License described in the LGPL.txt 
package hep.aida;


/**
 * User level interface to Histogram.
 * Provides the common functionality of the histogram-like classes.
 *
 * @author The AIDA team (http://aida.freehep.org/)
 *
 */
 
public interface IBaseHistogram {

  /**
   * Get the Histogram's title.
   * @return The Histogram's title.
   *
   */
    public String title();

  /**
   * Set the histogram title.
   * @param title The title.
   * @throws      IllegalArgumentEception If title cannot be changed.
   *
   */
    public void setTitle(String title) throws IllegalArgumentException;

  /**
   * Get the IAnnotation associated with the Histogram.
   * @return The IAnnotation.
   *
   */
    public IAnnotation annotation();

  /**
   * Get the Histogram's dimension.
   * @return The Histogram's dimension.
   *
   */ 
    public int dimension();

  /**
   * Reset the Histogram; as if just created.
   * @throws RuntimeException If something goes wrong.
   *
   */
    public void reset() throws RuntimeException;

  /**
   * Get the number of in-range entries in the Histogram.
   * @return The number of in-range entries.
   *
   */ 
    public int entries();
} // class or interface

