// AID-GENERATED
// =========================================================================
// This class was generated by AID - Abstract Interface Definition          
// DO NOT MODIFY, but use the org.freehep.aid.Aid utility to regenerate it. 
// =========================================================================

//  This file is part of the AIDA library
//  Copyright (C) 2002 by the AIDA team.  All rights reserved.
//  This library is free software and under the terms of the
//  GNU Library General Public License described in the LGPL.txt 
package hep.aida;


/**
 * Constants used throughout AIDA.
 *
 * @author The AIDA team (http://aida.freehep.org/)
 *
 */

public interface IConstants {

    public final static String AIDA_VERSION = "3.2.1";

    public final static int AIDA_VERSION_MAJOR = 3;

    public final static int AIDA_VERSION_MINOR = 2;
} // class or interface

