// AID-GENERATED
// =========================================================================
// This class was generated by AID - Abstract Interface Definition          
// DO NOT MODIFY, but use the org.freehep.aid.Aid utility to regenerate it. 
// =========================================================================

//  This file is part of the AIDA library
//  Copyright (C) 2002 by the AIDA team.  All rights reserved.
//  This library is free software and under the terms of the
//  GNU Library General Public License described in the LGPL.txt 
package hep.aida;


/**
 * Style for the part of the scene representing the data
 * (then histograms, functions, data point sets).
 *
 * @author The AIDA team (http://aida.freehep.org/)
 *
 */

public interface IDataStyle extends IBaseStyle {

  /**
   * Return various styles that may be used to 
   * customize the data representation.
   */
    public ILineStyle lineStyle();

    public IMarkerStyle markerStyle();

    public IFillStyle fillStyle();

  /**
   * Set various basic style on the data style.
   */
    public boolean setLineStyle(ILineStyle lineStyle);

    public boolean setMarkerStyle(IMarkerStyle markerStyle);

    public boolean setFillStyle(IFillStyle fillStyle);
} // class or interface

