// AID-GENERATED
// =========================================================================
// This class was generated by AID - Abstract Interface Definition          
// DO NOT MODIFY, but use the org.freehep.aid.Aid utility to regenerate it. 
// =========================================================================

//  This file is part of the AIDA library
//  Copyright (C) 2002 by the AIDA team.  All rights reserved.
//  This library is free software and under the terms of the
//  GNU Library General Public License described in the LGPL.txt 
package hep.aida;


/**
 * Style for all filled areas (boxes, regions, histograms, etc.)
 *
 * @author The AIDA team (http://aida.freehep.org/)
 */

public interface IFillStyle extends IBrushStyle {

  /**
   * Get a list of patterns available in this implementation.
   */
    public String[] availablePatterns();

  /** 
   * Get name of current pattern.
   */
    public String pattern();

  /**
   * Set current pattern, e.g. "crossHatch", "solid".
   * @return false if pattern not known to this implementation.
   */
    public boolean setPattern(String pattern);
} // class or interface

