// AID-GENERATED
// =========================================================================
// This class was generated by AID - Abstract Interface Definition          
// DO NOT MODIFY, but use the org.freehep.aid.Aid utility to regenerate it. 
// =========================================================================

//  This file is part of the AIDA library
//  Copyright (C) 2002 by the AIDA team.  All rights reserved.
//  This library is free software and under the terms of the
//  GNU Library General Public License described in the LGPL.txt 
package hep.aida;


/**
 * User's level interface of an IFilter.
 *
 * @author The AIDA team (http://aida.freehep.org/)
 *
 */

public interface IFilter {

  /**
   * Initialize the IFilter and associate it to an ITuple.
   * @param tuple The ITuple to which the IFilter is sssociated.
   * @throws      IllegalArgumentException If the IFilter and 
   *              the ITuple are not compatible.
   *
   */ 
    public void initialize(ITuple tuple) throws IllegalArgumentException;

  /**
   * Check if the IFilter accepts or not the data in the 
   * current row of the ITuple it is associated to.
   * @return <code>true</code> if the current data is accepted.
   * @throws RuntimeException if the IFilter has not been initialized.
   *
   */ 
    public boolean accept() throws RuntimeException;

   /**
    * Get the expression that defined the IFilter.
    * @return The expression.
    *
    */
    public String expression();
} // class or interface

