// AID-GENERATED
// =========================================================================
// This class was generated by AID - Abstract Interface Definition          
// DO NOT MODIFY, but use the org.freehep.aid.Aid utility to regenerate it. 
// =========================================================================

//  This file is part of the AIDA library
//  Copyright (C) 2002 by the AIDA team.  All rights reserved.
//  This library is free software and under the terms of the
//  GNU Library General Public License described in the LGPL.txt 
package hep.aida;


/**
 * The info class permits to access the info area of a region.
 * Through it legends, statistics, text could be displayed.
 * A legend is an association of a graphical marker and a text.
 *
 * @author The AIDA team (http://aida.freehep.org/)
 *
 */

public interface IInfo {

  /**
   * Clear the info area.
   */
    public void clear();

  /**
   * Add a text. The text is appended to existing info elements.
   */
    public void addText(String text);

  /**
   * Add a marker, line or fill area legend.
   * The legend is appended to existing elements.
   */
    public void addLegend(IMarkerStyle style, String description);

    public void addLegend(ILineStyle style, String description);

    public void addLegend(IFillStyle style, String description);
} // class or interface

