// AID-GENERATED
// =========================================================================
// This class was generated by AID - Abstract Interface Definition          
// DO NOT MODIFY, but use the org.freehep.aid.Aid utility to regenerate it. 
// =========================================================================

//  This file is part of the AIDA library
//  Copyright (C) 2002 by the AIDA team.  All rights reserved.
//  This library is free software and under the terms of the
//  GNU Library General Public License described in the LGPL.txt 
package hep.aida;


/**
 * Style for the part of the scene representing the info area.
 *
 * @author The AIDA team (http://aida.freehep.org/)
 *
 */

public interface IInfoStyle extends IBaseStyle {

    public ITextStyle textStyle();

    public boolean setTextStyle(ITextStyle textStyle);
} // class or interface

