// AID-GENERATED
// =========================================================================
// This class was generated by AID - Abstract Interface Definition          
// DO NOT MODIFY, but use the org.freehep.aid.Aid utility to regenerate it. 
// =========================================================================

//  This file is part of the AIDA library
//  Copyright (C) 2002 by the AIDA team.  All rights reserved.
//  This library is free software and under the terms of the
//  GNU Library General Public License described in the LGPL.txt 
package hep.aida;


/**
 * Style for all lines (axis lines, legend box outlines, etc.)
 *
 * @author The AIDA team (http://aida.freehep.org/)
 */

public interface ILineStyle extends IBrushStyle {

  /**
   * Get list of line types supported by this implementation.
   */
    public String[] availableLineTypes();

  /**
   * Get line type currently in use.
   */
    public String lineType();

  /**
   * Get current line thickness.
   */
    public int thickness();

  /**
   * Set current line type e.g. "dotted".
   * @return false if line type not known to this implementation.
   */
    public boolean setLineType(String newLineType);

  /**
   * Set thickness (exact meaning is implementation-dependent, 
   * but <0 means invisible).
   * @return false if value not supported by this implementation.
   */
    public boolean setThickness(int newThickness);
} // class or interface

