// AID-GENERATED
// =========================================================================
// This class was generated by AID - Abstract Interface Definition          
// DO NOT MODIFY, but use the org.freehep.aid.Aid utility to regenerate it. 
// =========================================================================

//  This file is part of the AIDA library
//  Copyright (C) 2002 by the AIDA team.  All rights reserved.
//  This library is free software and under the terms of the
//  GNU Library General Public License described in the LGPL.txt 
package hep.aida;


/**
 * Style for all markers (histo representation, legend box etc.)
 *
 * @author The AIDA team (http://aida.freehep.org/)
 */

public interface IMarkerStyle extends IBrushStyle {

  /**
   * Get list of shapes available in this implementation.
   */
    public String[] availableShapes();

  /**
   * Get current marker shape.
   */
    public String shape();

  /**
   * Set current marker shape, e.g. "openCircle". 
   * @return false if shape not available in this implementation.
   */
    public boolean setShape(String shape);
} // class or interface

