// AID-GENERATED
// =========================================================================
// This class was generated by AID - Abstract Interface Definition          
// DO NOT MODIFY, but use the org.freehep.aid.Aid utility to regenerate it. 
// =========================================================================

//  This file is part of the AIDA library
//  Copyright (C) 2002 by the AIDA team.  All rights reserved.
//  This library is free software and under the terms of the
//  GNU Library General Public License described in the LGPL.txt 
package hep.aida;


/**
 * User level interface to plotter style.
 * A plotter style permit to customize various part
 * of the plotting "scene" (axes, titles, data 
 * representations, etc...)
 *
 * @author The AIDA team (http://aida.freehep.org/)
 *
 */

public interface IPlotterStyle extends IBaseStyle {

  /** 
   * Get style of various plotting scene parts.
   */
    public IDataStyle dataStyle();

    public IAxisStyle xAxisStyle();

    public IAxisStyle yAxisStyle();

    public IAxisStyle zAxisStyle();

    public ITitleStyle titleStyle();

    public IInfoStyle infoStyle();

  /** 
   * Set style of various plotting scene parts.
   */
    public boolean setDataStyle(IDataStyle dataStyle);

    public boolean setAxisStyleX(IAxisStyle xAxisStyle);

    public boolean setAxisStyleY(IAxisStyle yAxisStyle);

    public boolean setAxisStyleZ(IAxisStyle zAxisStyle);

    public boolean setTitleStyle(ITitleStyle textStyle);

    public boolean setInfoStyle(IInfoStyle infoStyle);
} // class or interface

