// AID-GENERATED
// =========================================================================
// This class was generated by AID - Abstract Interface Definition          
// DO NOT MODIFY, but use the org.freehep.aid.Aid utility to regenerate it. 
// =========================================================================

//  This file is part of the AIDA library
//  Copyright (C) 2002 by the AIDA team.  All rights reserved.
//  This library is free software and under the terms of the
//  GNU Library General Public License described in the LGPL.txt 
package hep.aida;


/**
 * Interface to permit customization of the layout
 * of scene objects.
 *
 * @author The AIDA team (http://aida.freehep.org/)
 *
 */

public interface IPlotterLayout {

  /**
   * Return to original (construction time) state. Explicitly 
   * set parameters will be set to defaults and may be overridden 
   */
    public void reset();

  /**
   * Set a parameter. 
   * @param paramName Name of the parameter.
   * @param options String of options.
   * @return false if parameter (or its options) unknown or invalid.
   */
    public boolean setParameter(String paramName, double paramValue);

  /** 
   * Get parameter value.
   */
    public double parameterValue(String paramName);

  /**
   * Get list of the available parameters (implementation-dependent)
   */
    public String[] availableParameters();
} // class or interface

