// AID-GENERATED
// =========================================================================
// This class was generated by AID - Abstract Interface Definition          
// DO NOT MODIFY, but use the org.freehep.aid.Aid utility to regenerate it. 
// =========================================================================

//  This file is part of the AIDA library
//  Copyright (C) 2002 by the AIDA team.  All rights reserved.
//  This library is free software and under the terms of the
//  GNU Library General Public License described in the LGPL.txt 
package hep.aida;


/**
 * Factory for plotter and styles.
 *
 * @author The AIDA team (http://aida.freehep.org/)
 */

public interface IPlotterFactory {

   /** 
                    A plotter is in general managed by a GUI.
                    The "name" of the plotter could be used as 
                    the string identifier for the GUI plotter widget.
                    If "" is passed, some default plotter is used.
    */

    public IPlotter create();
   /** 
     * @param name  A string identifier. 
                    A plotter is in general managed by a GUI.
                    The "name" of the plotter could be used as 
                    the string identifier for the GUI plotter widget.
                    If "" is passed, some default plotter is used.
    */

    public IPlotter create(String name);

   /** 
    * Create various basic styles. 
    * The returned styles are not managed by the plotter.
    * A user have to delete these objects.
    */
    public IMarkerStyle createMarkerStyle();

    public ITextStyle createTextStyle();

    public ILineStyle createLineStyle();

    public IFillStyle createFillStyle();

   /**
    * Create various "scene part" styles.
    * The returned styles are not managed by the plotter.
    */ 
    public IDataStyle createDataStyle();

    public IAxisStyle createAxisStyle();

    public ITitleStyle createTitleStyle();

   /**
    * Create a global plotter style.
    * The returned style is not managed by the plotter.
    */ 
    public IPlotterStyle createPlotterStyle();
} // class or interface

